# Generated by Django 6.0.3 on 2026-03-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_lat_user_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger')], default='passenger', max_length=10),
        ),
    ]
