# Generated by Django 6.0.3 on 2026-03-17 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpool', '0001_initial'),
        ('network', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolrequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpoolrequest',
            name='pickup_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='network.node'),
        ),
        migrations.AddField(
            model_name='offer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.carpoolrequest'),
        ),
        migrations.AddField(
            model_name='offer',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
        migrations.AddField(
            model_name='rating',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_drop', to='network.node'),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_pickup', to='network.node'),
        ),
        migrations.AddField(
            model_name='ride',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
        migrations.AddField(
            model_name='rating',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carpool.ride'),
        ),
    ]
