# Generated by Django 6.0.3 on 2026-03-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
