# Generated by Django 6.0.3 on 2026-03-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.JSONField(blank=True, default=list)),
                ('route_index', models.IntegerField(default=0)),
                ('max_passengers', models.IntegerField()),
                ('current_passengers', models.IntegerField(default=0)),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.node')),
            ],
        ),
    ]
